<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WargaSeeder extends Seeder
{
    public function run(): void
    {
        $warga = [
            // Keluarga 1 - Ahmad Fauzi (4 orang)
            [
                'warga_nama' => 'Ahmad Fauzi',
                'warga_nik' => '3507011980010001',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1980-01-15',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Wiraswasta',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '081234567890',
                'warga_email' => 'ahmad.fauzi@email.com',
                'keluarga_id' => 1,
                'rumah_id' => 1,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Siti Nurhaliza',
                'warga_nik' => '3507011985020002',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1985-02-20',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Guru',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '082345678901',
                'warga_email' => 'siti.nur@email.com',
                'keluarga_id' => 1,
                'rumah_id' => 1,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Rizki Ahmad Fauzi',
                'warga_nik' => '3507012010030003',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2010-03-10',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'SMP',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 1,
                'rumah_id' => 1,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Zahra Siti Nurhaliza',
                'warga_nik' => '3507012015040004',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2015-04-25',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'SD',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 1,
                'rumah_id' => 1,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Keluarga 2 - Budi Santoso (3 orang)
            [
                'warga_nama' => 'Budi Santoso',
                'warga_nik' => '3507011978050005',
                'warga_tempat_lahir' => 'Surabaya',
                'warga_tanggal_lahir' => '1978-05-12',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S2',
                'warga_pekerjaan' => 'PNS',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '083456789012',
                'warga_email' => 'budi.santoso@email.com',
                'keluarga_id' => 2,
                'rumah_id' => 2,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Rina Wati',
                'warga_nik' => '3507011982060006',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1982-06-18',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Dokter',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '084567890123',
                'warga_email' => 'rina.wati@email.com',
                'keluarga_id' => 2,
                'rumah_id' => 2,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Dimas Budi Santoso',
                'warga_nik' => '3507012012070007',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2012-07-08',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'SMP',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 2,
                'rumah_id' => 2,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Keluarga 3 - Eko Prasetyo (5 orang)
            [
                'warga_nama' => 'Eko Prasetyo',
                'warga_nik' => '3507011975080008',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1975-08-22',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Pengusaha',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '085678901234',
                'warga_email' => 'eko.prasetyo@email.com',
                'keluarga_id' => 3,
                'rumah_id' => 3,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Lina Marlina',
                'warga_nik' => '3507011977090009',
                'warga_tempat_lahir' => 'Bandung',
                'warga_tanggal_lahir' => '1977-09-15',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'D3',
                'warga_pekerjaan' => 'Ibu Rumah Tangga',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '086789012345',
                'warga_email' => 'lina.marlina@email.com',
                'keluarga_id' => 3,
                'rumah_id' => 3,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Farhan Eko Prasetyo',
                'warga_nik' => '3507012008100010',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2008-10-05',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'SMA',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 3,
                'rumah_id' => 3,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Aisha Lina Marlina',
                'warga_nik' => '3507012013110011',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2013-11-20',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'SD',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 3,
                'rumah_id' => 3,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Rafif Eko Prasetyo',
                'warga_nik' => '3507012018120012',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2018-12-12',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'TK',
                'warga_pekerjaan' => 'Belum Bekerja',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 3,
                'rumah_id' => 3,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Keluarga 4 - Dewi Lestari (2 orang)
            [
                'warga_nama' => 'Dewi Lestari',
                'warga_nik' => '3507011990010013',
                'warga_tempat_lahir' => 'Jakarta',
                'warga_tanggal_lahir' => '1990-01-30',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Karyawan Swasta',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => '087890123456',
                'warga_email' => 'dewi.lestari@email.com',
                'keluarga_id' => 4,
                'rumah_id' => 4,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Maya Sari',
                'warga_nik' => '3507011992020014',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1992-02-14',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Islam',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Desainer Grafis',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => '088901234567',
                'warga_email' => 'maya.sari@email.com',
                'keluarga_id' => 4,
                'rumah_id' => 4,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Keluarga 5 - Hendra Wijaya (6 orang)
            [
                'warga_nama' => 'Hendra Wijaya',
                'warga_nik' => '3507011970030015',
                'warga_tempat_lahir' => 'Surabaya',
                'warga_tanggal_lahir' => '1970-03-08',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'S2',
                'warga_pekerjaan' => 'Dosen',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '089012345678',
                'warga_email' => 'hendra.wijaya@email.com',
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Maria Wijaya',
                'warga_nik' => '3507011972040016',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '1972-04-12',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'S1',
                'warga_pekerjaan' => 'Perawat',
                'warga_status_perkawinan' => 'Kawin',
                'warga_telepon' => '081123456789',
                'warga_email' => 'maria.wijaya@email.com',
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Kevin Hendra Wijaya',
                'warga_nik' => '3507012005050017',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2005-05-20',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'SMA',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Michelle Maria Wijaya',
                'warga_nik' => '3507012009060018',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2009-06-15',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'SMP',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Jonathan Hendra Wijaya',
                'warga_nik' => '3507012014070019',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2014-07-22',
                'warga_jenis_kelamin' => 'L',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'SD',
                'warga_pekerjaan' => 'Pelajar',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'warga_nama' => 'Stefani Maria Wijaya',
                'warga_nik' => '3507012019080020',
                'warga_tempat_lahir' => 'Malang',
                'warga_tanggal_lahir' => '2019-08-10',
                'warga_jenis_kelamin' => 'P',
                'warga_agama' => 'Kristen',
                'warga_pendidikan' => 'TK',
                'warga_pekerjaan' => 'Belum Bekerja',
                'warga_status_perkawinan' => 'Belum Kawin',
                'warga_telepon' => null,
                'warga_email' => null,
                'keluarga_id' => 5,
                'rumah_id' => 5,
                'warga_status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('t_warga')->insert($warga);
    }
}
